api_key:
api_base: http://127.0.0.1:1234/v1
model: qwen3-4B-mlx
context_max_tokens: 32768
assistant_minimum_context_tokens: 2048
stop_words:
- |2-

  <|im_start|>
- <|im_end|>
session_db_url: "/Users/tg/Library/Application Support/com.awful-sec.aj/aj.db"
session_name: None
